# The public documentation URL, used for sitemap.xml
url: "http://docs.telerik.com/kendo-ui"

# Exclude files which should not be in the output
exclude: [readme.md, Gemfile, Gemfile.lock,api_sort.rb]
navigation:
## List your directory names and order here, like this:
    "*install":
        title: "Installation and Upgrade"
        position: 2
    "*basics":
        title: "The Basics"
        position: 3
    "*api":
        title: "API"
    "*getting-started":
        title: "Getting Started"
    "*tutorials":
        title: "Tutorials"
    "getting-started/using-kendo-with":
        title: "Using Kendo With"
        position: 5
    "getting-started/web":
        title: "Web"
        position: 7
    "getting-started/framework":
        title: "Framework"
        position: 8
    "getting-started/dataviz":
        title: "DataViz"
        position: 9
    "getting-started/mobile":
        title: "Mobile"
        position: 10
    "getting-started/wrappers":
        title: "Wrappers"
        position: 11
    "getting-started/accessibility":
        title: "Make your Kendo UI Project Accessible"
        position: 14
    "getting-started/mobile/listview":
        title: "Mobile ListView"
        position: 9
    "*typescript":
        title: "TypeScript"
    "*asp.net":
        title: "ASP.NET"
    "*widgets":
        title: "Widgets"
    "*tags":
        title: "Tags"
    "*aspnet-mvc":
        title: "ASP.NET MVC"
    "*php":
        title: "PHP"
    "*jsp":
        title: "JSP"
    "*mobileactionsheet":
        title: "MobileActionSheet"
    "*mobileapplication":
        title: "MobileApplication"
    "*mobilebuttongroup":
        title: "MobileButtonGroup"
    "*mobiledrawer":
        title: "MobileDrawer"
    "*mobilenavbar":
        title: "MobileNavBar"
    "*mobilelayout":
        title: "MobileLayout"
    "*mobilemodalview":
        title: "MobileModalView"
    "*mobilepopover":
        title: "MobilePopOver"
    "*mobilescrollview":
        title: "MobileScrollView"
    "*mobilesplitview":
        title: "MobileSplitView"
    "*mobileswitch":
        title: "MobileSwitch"
    "*mobiletabstrip":
        title: "MobileTabStrip"
    "*mobilelistview":
        title: "MobileListView"
    "*mobileview":
        title: "MobileView"
    "*mobilebutton":
        title: "MobileButton"
    "*barcode":
        title: "Barcode"
    "*stockchart":
        title: "Stock Chart"
    "*chart":
        title: "Chart"
    "*diagram":
        title: "Diagram"
    "*geometry":
        title: "Geometry"
    "*drawing":
        title: "Drawing"
    "*lineargauge":
        title: "LinearGauge"
    "*treemap":
        title: "TreeMap"
    "*map":
        title: "Map"
    "*qrcode":
        title: "QRCode"
    "*radialgauge":
        title: "RadialGauge"
    "*sparkline":
        title: "Sparkline"
    "*stockchart":
        title: "StockChart"
    "*hierarchicaldatasource":
        title: "HierarchicalDataSource"
    "*datasource":
        title: "DataSource"
    "*draganddrop":
        title: "Drag and Drop"
    "*fx":
        title: "FX"
    "*globalization":
        title: "Globalization"
    "*mvvm":
        title: "MVVM"
    "*spa":
        title: "SPA"
    "*templates":
        title: "Templates"
    "*validator":
        title: "Validator"
    "*autocomplete":
        title: "AutoComplete"
    "*button":
        title: "Button"
    "*calendar":
        title: "Calendar"
    "*colorpalette":
        title: "ColorPalette"
    "*flatcolorpicker":
        title: "FlatColorPicker"
    "*colorpicker":
        title: "ColorPicker"
    "*combobox":
        title: "ComboBox"
    "*datepicker":
        title: "DatePicker"
    "*datetimepicker":
        title: "DateTimePicker"
    "*dropdownlist":
        title: "DropDownList"
    "*editor":
        title: "Editor"
    "*gantt":
        title: "Gantt"
    "*pivotgrid":
        title: "PivotGrid"
    "*grid":
        title: "Grid"
    "*listview":
        title: "ListView"
    "*maskedtextbox":
        title: "MaskedTextBox"
    "*menu":
        title: "Menu"
    "*multiselect":
        title: "MultiSelect"
    "*notification":
        title: "Notification"
    "*numerictextbox":
        title: "NumericTextBox"
    "*panelbar":
        title: "PanelBar"
    "*pivotdatasource":
        title: "PivotDataSource"
    "*pivotgrid":
        title: "PivotGrid"
    "*progressbar":
        title: "ProgressBar"
    "*rangeslider":
        title: "RangeSlider"
    "*scheduler":
        title: "Scheduler"
    "*slider":
        title: "Slider"
    "*sortable":
        title: "Sortable"
    "*splitter":
        title: "Splitter"
    "*tabstrip":
        title: "TabStrip"
    "*timepicker":
        title: "TimePicker"
    "*tooltip":
        title: "Tooltip"
    "*toolbar":
        title: "ToolBar"
    "*treeview":
        title: "TreeView"
    "*upload":
        title: "Upload"
    "*window":
        title: "Window"
    "*hello-kendo-ui":
        title: "Hello Kendo UI"
    "*home-page":
        title: "Home Page"
    "*order-page":
        title: "Order Page"
    "*localization":
        title: "Localization"
    "*webforms":
        title: "ASP.NET Web Forms"
    "getting-started/using-kendo-with/aspnet-mvc/vs-integration":
        title: "Visual Studio Integration"
        position: 9
    "getting-started/using-kendo-with/aspnet-mvc/migration":
        title: "Migrate From Telerik Extensions"
        position: 12
    "getting-started/using-kendo-with/aspnet-mvc/helpers":
        title: "View Helpers"
        position: 11
    "getting-started/using-kendo-with/aspnet-mvc/tutorial-saleshub":
        title: "Tutorial: Build the Sales Hub Project"
        position: 20
    "getting-started/using-kendo-with/aspnet-mvc/tutorial-kendo-music-store":
        title: "Tutorial: Build the Kendo Music Store"
        position: 20
    "getting-started/using-kendo-with/aspnet-mvc/tutorial-kendo-music-store/music-store-web":
        title: "Build the Web Application"
        position: 2
    "getting-started/using-kendo-with/aspnet-mvc/tutorial-kendo-music-store/music-store-dashboard":
        title: "Build the Dashboard"
        position: 3
## The application virtual path
baseurl: /kendo-ui

## Assign layout and category per different paths
defaults:
-
    scope:
        path: "getting-started"
    values:
        layout: "page"
        category: "getting-started"
-
    scope:
        path: "api"
    values:
        layout: "page"
        category: "api"
-
    scope:
        path: "tutorials"
    values:
        layout: "page"
        category: "tutorials"

type_links:
    "kendo.Class": "/api/framework/class"
    "kendo.data.DataSource": "/api/framework/datasource"
    "Array": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array"
    "Boolean": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean"
    "Function": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function"
    "jQuery": "http://api.jquery.com/Types/#jQuery"
    "Object": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object"
    "Number": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number"
    "String": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String"

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

# The google services configuration
google_tag_manager: GTM-6X92
google_custom_search: '001595215763381649090:eblhnfskwrk'

# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
